
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 829758
	#The name of the modpack
	modpackName = "DawnCraft"
	#The version of the modpack
	modpackVersion = "1.29"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

