
[default_gamerule]
	hasFallAnimation = true
	#Range: 0 ~ 100
	weightPenalty = 100
	disapleEntityUI = false
	keepSkills = false
	doVanillaAttack = true

[loot]
	skill_book_mob_loot = false
	skill_book_chest_loot = false

