
[general]
	#Entities that follow the player after sneak right-clicked. (uses the string format and either classname e.g. "Villager" or registry name e.g. "minecraft:villager")
	entityWhitelist = ["simple_mobs:josslyn_mc"]
	#Should following entities teleport when too far away (like wolves)?
	shouldTeleport = true
	#How far away do entities need to be away to teleport?
	#Range: 0.0 ~ 255.0
	teleportDistance = 30.0
	#How far away do entities need to be away to stop following?
	#Range: 0.0 ~ 255.0
	stopFollowDistance = 60.0

