
["Raid settings"]
	#How many Igniters each wave
	#Requires game restart
	#Must have no more and no less than 8 integers
	igniter_raidcount = [0, 0, 1, 2, 0, 2, 1, 4]
	#Should the Magispeller only be allowed to fight once all other raiders in the wave are killed?
	#Default = true
	magispeller_forcefield = true
	#Controls if Magispeller should despawn if it spawns in the 7th wave before the bonus wave.
	#Overrides magispeller_raidcount
	#Default = true
	magispeller_onlyOneAllowed = true
	#How many Magispellers each wave
	#Requires game restart
	#Must have no more and no less than 8 integers
	magispeller_raidcount = [0, 0, 0, 0, 0, 0, 0, 0]
	#How many Twittollagers each wave
	#Requires game restart
	#Must have no more and no less than 8 integers
	twittollager_raidcount = [0, 0, 0, 0, 1, 0, 2, 1]
	#How many Spiritcallers each wave
	#Requires game restart
	#Must have no more and no less than 8 integers
	spiritcaller_raidcount = [0, 0, 0, 0, 0, 0, 0, 0]
	#Controls if Spiritcaller should despawn if it spawns in the 7th wave before the bonus wave.
	#Overrides spiritcaller_raidcount
	#Default = true
	spiritcaller_onlyOneAllowed = true
	#Should the Spiritcaller only be allowed to fight once all other raiders in the wave are killed?
	#Default = true
	spiritcaller_forcefield = true

	["Raid settings"."Boss Randomizer settings"]
		#Mobs put in this list will be randomly selected by the Boss Randomizer.
		#Format must be like 'examplemod:entity'. Example: "minecraft:zombie"
		#You can use the /summon command to scroll through and find the IDs for mobs you want!
		#Invalid entity registry names will spawn the boss randomizer itself as an illager. Same goes for if this list is empty
		#Only entities extending the Abstract Raider class will actually join the Raid upon spawning
		#Requires game restart
		bossrandomizer_bosstypes = []
		#How many Boss Randomizers each wave
		#Requires game restart
		#Must have no more and no less than 8 integers
		#Note that Boss Randomizers on the final Raid wave will be considered the 'Final Boss'
		bossrandomizer_raidcount = [0, 0, 0, 0, 0, 0, 0, 1]
		#Mobs put in this list will be randomly selected by the Final Boss Randomizer. Only insanely powerful mobs like the Magispeller should go here
		#Format must be like 'examplemod:entity'. Example: "minecraft:zombie"
		#You can use the /summon command to scroll through and find the IDs for mobs you want!
		#Invalid entity registry names will spawn the boss randomizer itself as an illager. Same goes for if this list is empty
		#Only entities extending the Abstract Raider class will actually join the Raid upon spawning
		#Requires game restart
		bossrandomizer_finalbosstypes = ["illageandspillage:magispeller"]
		#Controls if the Boss Randomizer should despawn if it spawns in the 7th wave before the bonus wave.
		#Overrides bossrandomizer_raidcount
		#Default = true
		bossrandomizer_onlyOneAllowed = true
		#Should Boss Randomizer be allowed to spawn special bosses depending on the calendar date?
		#Default = true
		bossrandomizer_seasonalBosses = true
		#Should Boss Randomizer broadcast the spawning of a boss with a sound?
		#Default = true
		bossrandomizer_broadcastBossSpawn = true

	["Raid settings"."Spiritcaller settings"]
		#Mobs put in this list have 'souls' the Spiritcaller can steal.
		#Format must be like 'examplemod:entity'. Example: "minecraft:zombie"
		#You can use the /summon command to scroll through and find the IDs for mobs you want!
		#Requires game restart
		spiritcaller_stealableMobs = ["minecraft:villager", "minecraft:wandering_trader", "minecraft:pig", "minecraft:cow", "minecraft:sheep", "minecraft:chicken", "minecraft:cat", "minecraft:zombie", "minecraft:husk", "minecraft:skeleton", "minecraft:stray", "minecraft:creeper", "minecraft:spider", "minecraft:enderman"]
		#Mobs put in this list won't be attacked by mobs attacking the Spiritcaller, when their souls are taken.
		#Format must be like 'examplemod:entity'. Example: "minecraft:zombie"
		#You can use the /summon command to scroll through and find the IDs for mobs you want!
		#Only actually happens if the mob is in spiritcaller_stealableMobs
		#Requires game restart
		spiritcaller_wontAttack = ["minecraft:villager", "minecraft:wandering_trader"]

	["Raid settings"."Misc settings"]
		#Controls if Igniter should cause block damage with its fireballs.
		#As of now its fireballs will still use the normal fire block; basically don't set this to true if you care about your world.
		#Default = false
		#Note that Igniter's block damage is still affected by the mobGriefing gamerule
		igniter_canBurnBlocks = false

