#You should only need to use this option in very edge case scenarios. This option transforms all structures in this list to shrines:deleted_structures when Minecraft updates your world from 1.18.1 or below to 1.18.2 or above
removed_structures = []
#All structures in this list won't spawn in worlds anymore. Already generated structures won't disappear and toggling this option won't cause issues
disabled_structures = []
#You should only need to change this if you want to rerun the updater task on next Minecraft start. In fact it does exactly that. See here: https://silverminer007.github.io/ShrinesWiki/wiki/en_us/users/structureUpdater1.18.2.html
run_structure_updater = true
#An additional spawn requirement for shrines structures. This only affects structures which use the shrines:min_structure_distance spawn criteria and they're is set to a negative value. This is the case for all shrines default structures in default configuration. Set this to a negative value to disable min structure distance entirely. 
#If you activate this option, all buildings will appear much less frequently. A tenfold increase is typical
#Range: -1 ~ 100
min_structure_distance = -1

